name: practical_machine_learning
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - keras
  - tensorflow
  - umap-learn
  - jupyter
  - jupyterlab
